resources:
  - name: pbag
    type: PropertyBag
    configuration:
      conf1: "something"
pipelines: 
  - name: stressTestPip1
    steps:
      - name: s1
        type: Bash
        execution:
          onExecute:
            - echo "done"
        configuration:
          outputResources:
            - name: pbag
      - name: s2
        type: Bash
        execution:
          onExecute:
            - echo "done"
        configuration:
          inputResources:
            - name: pbag
