language: python
build_image: drydock/u12pyt:prod
python:
  - 2.6
  - 2.7
  #- 3.2
  #- 3.3
  #- 3.4
  #- pypy

# Make folders for the reports
before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

script:
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  - echo $COMMITTER
  - echo $LAST_AUTHOR
  - sleep 1
  # exclude
#branches:
 #  - TEST


#cache: true
#integrations:
#  notifications:
#    - integrationName: hipchat
#      type: hipchat
#      recipients:
#        - "@VootlaChaitanya"
#        - "#roomOne"
#      on_success: always
#      on_failure: always
resources:
  - name: pipelines-demo-image-mini2
    type: image
    integration: shipdeploy
    pointer:
      sourceName: "shippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamplesshippablesamples/samplepipelinesdemo"
      isPull: false
    seed:
      versionName: "latest"

jobs:
  - name: pipelines-demo-manifest-mini2
    type: manifest
    steps:
     - IN: pipelines-demo-image-mini
     - TASK: managed
    on_success:
     - NOTIFY: irc-mini
